# 使用官方 Python 运行时作为父镜像
FROM python:3.8-slim-buster

# 设置工作目录为 /app
WORKDIR /app

# 将当前目录内容复制到容器的 /app 中
COPY . /app

# 安装你需要的任何包
RUN pip install --no-cache-dir -r requirements.txt

# 设置环境变量
ENV NAME World

# 运行你的应用程序
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]