services :
  UserService :
    image : "law/userservice:v1"
    container_name: user-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 512M

  LegalConsultationService:
    image : "law/legalconsultationservice:v1"
    container_name: legal-consultation-service
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 512M

  DocumentManagementService:
    image : "law/documentmanagement:v1"
    container_name: document-management-service
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 512M


networks:
  lawnet :
    driver: "bridge"