FROM openjdk:17-jdk-slim
MAINTAINER incypio.com
COPY target/LegalConsultationService-0.0.1-SNAPSHOT.jar LegalConsultationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/LegalConsultationService-0.0.1-SNAPSHOT.jar"]